Moved to Spring Boot project, created a CRUD end-point for Weather class
JeJutic/pan-artem-tinkoff pull request #3
Opened 2023-09-27 16:07 UTC by JeJutic

Based on Spring Initializr. Created a Spring Controller for CRUD operations. Used an additional DTO for requesting only certain fields in request bodies. Used jakarta.validation.

2023-10-02 10:35 UTC, EMDavl requested changes

2023-10-02 10:35 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +public class CrudController {
Принято выносить логику в сервисы, оставляя контроллерам только обслуживание запросов: получить запрос, отправить какой-то ответ.

Это помогает абстрагироваться от способа получения данных и повышает возможность переиспользования кода, т.е не важно откуда к тебе пришел запрос Rest / Soap / т.д. тебе не надо повторно писать реализацию, ты просто делегируешь запрос в сервис. Ну и взаимодействие с БД соответственно переносится на уровень репозитория

https://stackoverflow.com/a/38678061/16006138
https://stackoverflow.com/a/9633619/16006138

2023-10-02 10:35 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +        data.add(new Weather(weatherDto.id(), city, weatherDto.temperature(), weatherDto.dateTime()));
> weatherDto.id()

Лучше будет генерировать id на бэке, а не принимать от пользователя

2023-10-02 10:35 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +            if (weather.getId().equals(weatherDto.id()) &&
Надо бы добавить обработку ситуации, когда по переданному id погода привязана к другому городу

2023-10-02 10:35 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +        data.add(new Weather(weatherDto.id(), city, weatherDto.temperature(), weatherDto.dateTime()));
Думаю, что тут тоже есть смысл добавить проверку id на уникальность или генерировать id на бэке

2023-10-02 10:35 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +    private ResponseEntity<Weather> getWeather(
Обычно методы контроллеров делают публичными

2023-10-02 10:35 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +public class CrudController {
Надо добавить `ExceptionHandler`'ы для ошибок, чтобы возвращался красивый ответ, а не 
<img width="664" alt="image" src="https://github.com/JeJutic/pan-artem-tinkoff/assets/79557554/fd088c72-60a7-453f-9f05-8284941b25a5">

2023-10-02 13:58 UTC, JeJutic commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +public class CrudController {
Странно, что у Вас "страница не найдена", а не пустая страница (с кодом 404).
Чтобы сделать через `ExceptionHandler` мне тогда нужно в случае пустого Optional бросать исключение, но бросание исключения не в исключительных ситуациях - это ведь плохая практика?

2023-10-03 08:28 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +public class CrudController {
404 - статус ошибки, так что для пользователя это выглядит как ошибка / исключительная ситуация. 

Так что как раз можно считать что это исключительный случай - по заданному запросу не получилось найти данные, кинуть ошибку и обработать её так, чтобы в ответе было что-то понятное пользователю, напр 

```
{
    "message": "Weather for provided city not found"
}
```

2023-10-03 14:46 UTC, EMDavl approved these changes

2023-10-03 14:46 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/controller/CrudController.java
> +        if (optionalWeather.isEmpty()) {
Это тоже лучше в сервисе оставить

2023-10-06 12:36 UTC, merged