CRUD methods implemeted with Hibernate + Spring Data JPA and Spring Data JDBC
JeJutic/pan-artem-tinkoff pull request #6
Opened 2023-10-15 20:16 UTC by JeJutic

CRUD methods available from /v1/weather-type/{city} end-point.
Database tables are initialized with Liquibase changelogs.
You are able to select implementation with Spring's @Primary annotation on implementation class.

2023-10-22 19:21 UTC, EMDavl requested changes

2023-10-22 19:21 UTC, EMDavl commented on src/main/resources/changelog/main-db-changelog.xml
> +    <changeSet  id="city-table"  author="panart">
Лучше выносить ченжсеты в отдельные файлы (а еще лучше в директории под соотв. версии) и потом добавлять через include в основной ченжлог

Вот [еще некоторые рекомендации](https://habr.com/ru/articles/179425/). С 9 пунктом я тут не очень согласен, но в остальном вроде норм

2023-10-22 19:21 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/entity/CityEntity.java
> +public class CityEntity {
Постфикс Entity кажется излишним т.к. это уже отражено в пакете где находится класс

2023-10-22 19:21 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/entity/CityEntity.java
> +    private WeatherTypeEntity weatherTypeEntity;
Тут скорее должна быть связь один ко многим с `Weather`, появляется необходимость доработать приложение и обновить существующее взаимодействие с этой сущностью из прошлых домашек (CRUD для погоды)

2023-10-22 19:21 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/repository/WeatherTypeRepositoryJPA.java
> +        WeatherTypeEntity weatherTypeEntity = weatherTypeEntityRepository
Надо либо получать `Collection<WeatherTypeEntity>` (скорее всего более конкретно - `List`), либо навесить Unique Constraint на столбец `description`, чтобы у нас гарантировано по одному описанию возвращался только один тип погоды. 

Какой из вариантов выбрать зависит от логики взаимодействия с типом погоды в твоем приложении

2023-10-22 19:21 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/repository/WeatherTypeRepositoryJdbc.java
> +                "SELECT COALESCE(SELECT id FROM city WHERE name = ? LIMIT 1)",
В БД id помечен как NOT NULL (`...  nullable="false" `), то coalesce необязателен

2023-10-22 19:21 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/repository/WeatherTypeRepositoryJdbc.java
> +public class WeatherTypeRepositoryJdbc implements WeatherTypeRepository {
Было необходимо реализовать на чистом Jdbc (71 минута лекции)

2023-10-22 19:21 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/repository/WeatherTypeRepositoryJPA.java
> +        return Optional.of(new WeatherTypeDto(weatherTypeEntity.getDescription()));
Тут лучше сделать что-то вроде кастомного запроса в JPA репозитории, возвращать из репозитория WeatherEntityType и уже в сервисе делать необходимый маппинг, т.к. репозиторий больше привязан именно к сущностям и дает абстрагированный доступ к конкретной сущности. Таким образом разные сервисы могут получать инфу о погоде по названию города и делать с ней что захотят (мапить, изменять и т.д.)

Что-то вроде
```
@Query("SELECT w FROM WeatherTypeEntity w LEFT JOIN w.cities c WHERE c.name = :cityName")
public WeatherTypeEntity getWeatherByCityName(@Param("cityName") String cityName);
```

Но вообще, кажется что еще лучше будет сделать запрос в CityRepository вида:

```
@EntityGraph(attributePath = "weatherTypeEntity")
public CityEntity findByName(String name);
```
Или
```
@Query("SELECT с FROM CityEntity c LEFT JOIN FETCH c.weatherEntityType WHERE c.name = :cityName")
public CityEntity findByNameWithWeatherFetching(@Param("cityName") String name);
```

И потом в сервисе вытащить из города его погоду

2023-10-22 19:21 UTC, EMDavl commented on src/main/java/pan/artem/tinkoff/repository/WeatherTypeRepositoryJPA.java
> +}
В целом большую часть логики маппинга, проставления полей и т.п. лучше вынести в сервис, оставив JPA репозиторию в большей степени взаимодействие с БД и в меньшей с сущностями приложения. Ну и тогда можно будет отказаться от этой реализации и использовать сразу `WeatherTypeEntityRepository` и аналогичный с городом

2023-10-31 17:18 UTC, JeJutic commented on src/main/java/pan/artem/tinkoff/repository/WeatherTypeRepositoryJPA.java
> +}
Нам ведь хотелось бы свести разные реализации работы с БД к одному интерфейсу. Подгонять свою JDBC реализацию под JpaRepository кажется не лучшей идеей, то есть нужен класс-адаптер для JPA-реализации (согласен, что классом адаптером не стоит делать наследник). Но в этом классе неизбежно будет логика маппинга и проставления полей. 
Конечно, не спорю с замечаниями об организации кода выше, но разве стоит класс-адаптер переносить в сервисы?

2023-11-06 09:47 UTC, merged